/**
 * Enum for all environment variable names
 * Single source of truth for env var names
 */
export enum EnvVar {
  // Core
  NODE_ENV = 'NODE_ENV',
  DATABASE_URL = 'DATABASE_URL',

  // LLM
  LLM_PROVIDER = 'LLM_PROVIDER',
  GEMINI_API_KEY = 'GEMINI_API_KEY',
  OPENAI_API_KEY = 'OPENAI_API_KEY',
  ANTHROPIC_API_KEY = 'ANTHROPIC_API_KEY',

  // GitHub
  GITHUB_TOKEN = 'GITHUB_TOKEN',
  GITHUB_TEST_OWNER = 'GITHUB_TEST_OWNER',
  GITHUB_TEST_REPO = 'GITHUB_TEST_REPO',

  // Docker
  DOCKER_HOST = 'DOCKER_HOST',
  DOCKER_SOCKET_PATH = 'DOCKER_SOCKET_PATH',
  DOCKER_CONTAINER_PREFIX = 'DOCKER_CONTAINER_PREFIX',
  DOCKER_CONTAINER_LIMIT = 'DOCKER_CONTAINER_LIMIT',
  DOCKER_IDLE_TIMEOUT = 'DOCKER_IDLE_TIMEOUT',
  DOCKER_DEFAULT_IMAGE = 'DOCKER_DEFAULT_IMAGE',

  // Retry Configuration
  LLM_MAX_RETRIES = 'LLM_MAX_RETRIES',
  LLM_INITIAL_RETRY_DELAY = 'LLM_INITIAL_RETRY_DELAY',
  LLM_MAX_RETRY_DELAY = 'LLM_MAX_RETRY_DELAY',
  LLM_RETRY_BACKOFF_FACTOR = 'LLM_RETRY_BACKOFF_FACTOR',

  // Testing
  TEST_API_KEY = 'TEST_API_KEY',

  // Logging
  LOG_LEVEL = 'LOG_LEVEL',

  // Debug
  DEBUG = 'DEBUG',
  DEBUG_MODE = 'DEBUG_MODE',
  PRISMA_DISABLE_WARNINGS = 'PRISMA_DISABLE_WARNINGS',
}
